// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQTHC0GKeIT062LVwveQ8BhipXNAvCrZg',
    appId: '1:982142896630:web:75f29e8ef0b2f4dbcf9fd7',
    messagingSenderId: '982142896630',
    projectId: 'storied-coil-456316-j1',
    authDomain: 'storied-coil-456316-j1.firebaseapp.com',
    storageBucket: 'storied-coil-456316-j1.firebasestorage.app',
    measurementId: 'G-6L68Z1626H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYRSHwPmMmQIgo1CTjwjHEQh2kQjTalSA',
    appId: '1:982142896630:android:dc7b0f676d852427cf9fd7',
    messagingSenderId: '982142896630',
    projectId: 'storied-coil-456316-j1',
    storageBucket: 'storied-coil-456316-j1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vhr7cyL3608s3g3NR2Av2gu8lSsEUX0',
    appId: '1:982142896630:ios:21b6d5bc3729b5b7cf9fd7',
    messagingSenderId: '982142896630',
    projectId: 'storied-coil-456316-j1',
    storageBucket: 'storied-coil-456316-j1.firebasestorage.app',
    androidClientId: '982142896630-9ljasc9c06jqdeno3invhh0hk32kmpcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivesense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9vhr7cyL3608s3g3NR2Av2gu8lSsEUX0',
    appId: '1:982142896630:ios:21b6d5bc3729b5b7cf9fd7',
    messagingSenderId: '982142896630',
    projectId: 'storied-coil-456316-j1',
    storageBucket: 'storied-coil-456316-j1.firebasestorage.app',
    androidClientId: '982142896630-9ljasc9c06jqdeno3invhh0hk32kmpcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivesense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQTHC0GKeIT062LVwveQ8BhipXNAvCrZg',
    appId: '1:982142896630:web:f65a190956a67588cf9fd7',
    messagingSenderId: '982142896630',
    projectId: 'storied-coil-456316-j1',
    authDomain: 'storied-coil-456316-j1.firebaseapp.com',
    storageBucket: 'storied-coil-456316-j1.firebasestorage.app',
    measurementId: 'G-1WCJMB2FZ9',
  );
}
